name: Demeter_Protocol

plugins:
  - name: foundry
  - name: solidity
  - name: etherscan
  - name: alchemy
  - name: tenderly
  - name: ganache

dependencies:
  - name: OpenZeppelin
    version: 4.9.5
    github: OpenZeppelin/openzeppelin-contracts

  - name: OpenZeppelin-Upgradable
    version: 4.9.5
    github: OpenZeppelin/openzeppelin-contracts-upgradeable

  - name: Uniswap-V3-Periphery
    version: 1.4.4
    npm: "@Uniswap/v3-periphery"

  - name: Uniswap-V3s
    version: 1.0.1
    npm: "@Uniswap/v3-core"
    
solidity:
  version: 0.8.16
  optimize: True
  import_remapping:
          - "@openzeppelin/contracts=OpenZeppelin/4.9.5"
          - "@openzeppelin/contracts-upgradeable=OpenZeppelin-Upgradable/4.9.5"
          - "@uniswap/v3-periphery/contracts=Uniswap-V3-Periphery/1.4.4"
          - "@uniswap/v3-core/contracts=Uniswap-V3/1.0.1"
test:
  mnemonic: test test test test test test test test test test test junk
  number_of_accounts: 10
  coverage:
    reports:
      terminal: True  # Disable the terminal table (True by default)
      xml: True  # Enable XML report (.build/coverage.xml)
      html: True  # Enable HTML report (.build/htmlcov)
ganache:
  fork:
    arbitrum:
      mainnet:
        upstream_provider: alchemy
  server:
    port: 8555 # Fork Server: http://localhost:8555