name: Demeter_Protocol

plugins:
  - name: foundry
  - name: solidity
  - name: etherscan
  - name: tenderly
  - name: polygon

dependencies:
  - name: OpenZeppelin
    version: 4.9.5
    github: OpenZeppelin/openzeppelin-contracts

  - name: OpenZeppelin-Upgradable
    version: 4.9.5
    github: OpenZeppelin/openzeppelin-contracts-upgradeable

  - name: Uniswap-V3-Periphery
    ref: 1.3.0
    github: "@Uniswap/v3-periphery"

  - name: Uniswap-V3
    ref: 1.0.0
    github: "@Uniswap/v3-core"

solidity:
  version: 0.8.16
  optimize: True

  import_remapping:
          - "@openzeppelin/contracts=OpenZeppelin/4.9.5"
          - "@openzeppelin/contracts-upgradeable=OpenZeppelin-Upgradable/4.9.5"
          - "@uniswap/v3-periphery/contracts=Uniswap-V3-Periphery/1.3.0"
          - "@uniswap/v3-core/contracts=Uniswap-V3/1.0.0"
test:
  mnemonic: test test test test test test test test test test test junk
  number_of_accounts: 10
  coverage:
    reports:
      terminal: True  # Disable the terminal table (True by default)
      xml: True  # Enable XML report (.build/coverage.xml)
      html: True  # Enable HTML report (.build/htmlcov)
deployments:
  polygon:
    mumbai:
      - contract_type: TokenUtils
        address: 0x160d4495A802E17608b26F3317a4E2B569E8997D

foundry:
  request_timeout: 20  # Defaults to 30
  fork_request_timeout: 600  # Defaults to 300
  base_fee: 0
  priority_fee: 0
  fork:
    arbitrum:
      mainnet:
        upstream_provider: alchemy
polygon:
  mumbai:
    gas_limit: auto
