# Brownie configuration file
# https://eth-brownie.readthedocs.io/en/stable/config.html
# required external contracts
dependencies:
  - OpenZeppelin/openzeppelin-contracts@5.0.2
  - OpenZeppelin/openzeppelin-contracts-upgradeable@5.0.2
  - Uniswap/uniswap-v3-periphery@1.3.0
  - Uniswap/uniswap-v3-core@1.0.0
  - OpenZeppelin/openzeppelin-contracts@4.9.2

pytest:
  # these settings replace the defaults when running pytest
  default_contract_owner: true
  reverting_tx_gas_limit: 6721975
  revert_traceback: true
compiler:
    solc:
        version: 0.8.26
        optimizer:
          enabled: true
          runs: 200
        remappings:
          - "@openzeppelin/contracts=node_modules/@openzeppelin/contracts"
          - "@openzeppelin/contracts-upgradeable=node_modules/@openzeppelin/contracts-upgradeable"
          - "@uniswap/v3-periphery/contracts=node_modules/@uniswap/v3-periphery/contracts"
          - "@uniswap/v3-core/contracts=node_modules/@uniswap/v3-core/contracts"


# automatically fetch contract sources from Etherscan
autofetch_sources: True

reports:
  exclude_contracts:
    - SafeMath
    - FullMath
    - TickMath
    - Address
    - OracleLibrary
    - LiquidityAmounts
    - MockToken
    - SafeERC20
    - TransparentUpgradeableProxy
    - Ownable
    - AddressUpgradeable
    - OwnableUpgradeable
    - SafeERC20Upgradeable
    - Clones